#include "scripts\base.inc"

global WinMenu;

#include "interface\verbbar\verbbar_functions.inc"

var verb_default = "Look at";

////////////////////////////////////////////////////////////////////////////////
on "LookAt"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption);
  Game.Interactive = false;

  actor.Talk("It's my favorite plastic fish.");
  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////

on "fish"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption + " with " + Command.Object2_caption);
  Game.Interactive = false;

  actor.Talk("I can't use the fish on itself!");

  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////

on "PickUp"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption + " with " + Command.Object2_caption);
  Game.Interactive = false;

  actor.Talk("I already have the fish!");

  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////

on "TalkTo"
{
  verb_setBar(Command.Verb + " " + Command.Object1_caption + " with " + Command.Object2_caption);
  Game.Interactive = false;

  actor.Talk("Hey there, my fishy friend.");

  verb_cleanBar();
  Game.Interactive = true;
}

////////////////////////////////////////////////////////////////////////////////
on "RightClick"
{
  verb_apply(verb_default);
}

////////////////////////////////////////////////////////////////////////////////
on "MouseEntry"
{
  verb_hover("Look at");
}

////////////////////////////////////////////////////////////////////////////////
on "MouseLeave"
{
  verb_unhover("Look at");
}
